"""
AETHERTRADE-SWARM — Strategy Pod Routes
GET /api/v1/strategies                      — all 9 pod statuses with allocation
GET /api/v1/strategies/{pod_name}           — detailed pod metrics
GET /api/v1/strategies/{pod_name}/signals   — pod signals
"""
from __future__ import annotations

from datetime import datetime

from fastapi import APIRouter, HTTPException, status

from api.auth import ApiKeyDep
from api.deps import SimulatorDep
from models.schemas import (
    PodListResponse,
    PodMetrics,
    PodName,
    PodSignalsResponse,
    SignalDetail,
)

router = APIRouter(prefix="/api/v1/strategies", tags=["strategies"])


def _build_pod_metrics(raw: dict) -> PodMetrics:
    return PodMetrics(
        pod_name=raw["pod_name"],
        display_name=raw["display_name"],
        status=raw["status"],
        regime_allocation=raw["regime_allocation"],
        ytd_return=raw["ytd_return"],
        sharpe_ratio=raw["sharpe_ratio"],
        max_drawdown=raw["max_drawdown"],
        win_rate=raw["win_rate"],
        signal_count=raw["signal_count"],
        last_signal_at=datetime.fromisoformat(raw["last_signal_at"]),
        description=raw["description"],
    )


@router.get("", response_model=PodListResponse, summary="All strategy pods")
async def list_strategies(
    _key: ApiKeyDep,
    sim: SimulatorDep,
) -> PodListResponse:
    """
    Returns metrics and current regime-adjusted allocation weights for all
    9 strategy pods. Ensemble allocation sum is regime-normalised.
    """
    pods_raw = sim.get_pod_metrics()
    pods = [_build_pod_metrics(p) for p in pods_raw]
    total_active = sum(1 for p in pods if p.status == "active")
    allocation_sum = round(sum(p.regime_allocation for p in pods), 4)

    return PodListResponse(
        pods=pods,
        total_active=total_active,
        ensemble_allocation_sum=allocation_sum,
    )


@router.get("/{pod_name}", response_model=PodMetrics, summary="Single pod metrics")
async def get_strategy(
    pod_name: str,
    _key: ApiKeyDep,
    sim: SimulatorDep,
) -> PodMetrics:
    """
    Returns detailed performance metrics for the specified strategy pod.
    Pod name must be one of: momentum, mean_reversion, macro, stat_arb,
    options_vol, behavioral, ai_ml, multi_factor, market_making.
    """
    valid_names = {p.value for p in PodName}
    if pod_name not in valid_names:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Unknown pod '{pod_name}'. Valid pods: {sorted(valid_names)}",
        )

    pods_raw = sim.get_pod_metrics()
    match = next((p for p in pods_raw if p["pod_name"] == pod_name), None)
    if match is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Pod '{pod_name}' not found.")

    return _build_pod_metrics(match)


@router.get("/{pod_name}/signals", response_model=PodSignalsResponse, summary="Pod signals")
async def get_pod_signals(
    pod_name: str,
    _key: ApiKeyDep,
    sim: SimulatorDep,
) -> PodSignalsResponse:
    """
    Returns current trading signals generated by the specified strategy pod,
    including per-asset direction, strength, confidence, and metadata.
    """
    valid_names = {p.value for p in PodName}
    if pod_name not in valid_names:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Unknown pod '{pod_name}'. Valid pods: {sorted(valid_names)}",
        )

    data = sim.get_pod_signals(pod_name)
    signals = [
        SignalDetail(
            asset=s["asset"],
            signal_name=s["signal_name"],
            direction=s["direction"],
            strength=s["strength"],
            confidence=s["confidence"],
            timestamp=datetime.fromisoformat(s["timestamp"]),
            metadata=s.get("metadata", {}),
        )
        for s in data["signals"]
    ]

    return PodSignalsResponse(
        pod_name=pod_name,
        signals=signals,
        aggregate_direction=data["aggregate_direction"],
        aggregate_strength=data["aggregate_strength"],
        generated_at=datetime.fromisoformat(data["generated_at"]),
    )
